name: CI

on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies in client directory
      run: |
        cd client
        npm install

    - name: Run tests in client directory
      run: |
        cd client
        # npm test

    - name: Install dependencies in server directory
      run: |
        cd server
        npm install

    - name: Run tests in server directory
      run: |
        cd server
        # npm test
