name: Debug Environment Variables

on:
  push:
    branches:
      - '*'

jobs:
  debug-env:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Environment Variables
      run: |
        echo "MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}"
        echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}"
        echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}"
