name: CI

on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: test_elcyckel
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies in client directory
      run: |
        cd client
        npm install

    - name: Run tests in client directory
      run: |
        cd client
        npm test

    - name: Install dependencies in server directory
      run: |
        cd server
        npm install

    - name: Run tests in server directory
      run: |
        cd server
        npm test
      
    - name: Debug Environment Variables
      run: |
        echo "MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}"
        echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}"
        echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}"

